export const fakeSliderData  = [
  {   id:0,
    img: "http://103.68.104.71//Admin/main/images/tt14672882/screen//hYCqInu2vhRysytIyifA41iw2Ek.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt14672882/poster//Ah3pJ3iuX28PKHjGLyIrEsFVq5q.jpg",
    title: "The Tomorrow Job",
    videoId: "zeKp69CY47Y",
    titleImg:"http://103.68.104.71//Admin/main/images/tt14672882/logo/tt14672882.png",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Tomorrow Job (2023)/The.Tomorrow.Job.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    rating: 4.85,
    year:2023,
    genre:[],
    category: "Si-Fi",
    length:"2h 12m",
  },
  {
    id:1,
    img: "http://103.68.104.71//Admin/main/images/tt0830515/screen//3CqMIX3ZlrD0pU3fpBL6DM0Cneb.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt0830515/poster//e3DXXLJHGqMx9yYpXsql1XNljmM.jpg",
    title: "James Bond Quantum of Solace",
    titleImg:"http://103.68.104.71//Admin/main/images/tt0830515/logo/tt0830515.png",
    videoId: "BBqYaFEWBxI",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2008/James Bond Quantum of Solace (2008)/James.Bond.Quantum.of.Solace.2008.720p.BRrip.x264.YIFY.mp4",
    rating: 3.75,
    year:2023,
    genre:[],
    category: "Action",
    length:"1h 39m",
  },
  {   id:2,
    img: "http://103.68.104.71//Admin/main/images/tt14799576/screen//baLw3zvl9R31Ocxh7uIpkk5cLVx.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt14799576/poster//dteXMzVY53GBHUgrR7vigAartsP.jpg",
    title: "The secret Kingdom",
    videoId: "h6TxL-C7zqA",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Secret Kingdom (2023)/The.Secret.Kingdom.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"http://103.68.104.71//Admin/main/images/tt14799576/logo/tt14799576.png",
    rating: 4.23,
    year:2021,
    genre:[],
    category: "Adventure",
    length:"2h 39m",
  },
  {   id:3,
    img: "http://103.68.104.71//Admin/main/images/tt13141250/screen//bQTfSXQrcVwXJ5TvNzbd3ioMnnM.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt13141250/poster//1VtHaELqLMovl8EueBWHDtihhzF.jpg",
    title: "The Retual Killer",
    videoId: "DIa__DpZX9U",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Ritual Killer (2023)/The.Ritual.Killer.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"http://103.68.104.71//Admin/main/images/tt13141250/logo/tt13141250.png",
    rating: 3.75,
    year:2013,
    genre:[],
    category: "Action",
    length:"1h 56m",
  },
  {   id:4,
    img:"http://103.68.104.71//Admin/main/images/tt7825076/screen//lOhyq1FqSlJe7li1G9ERebP0ukM.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt7825076/poster//q926UPyqeVrJ6Usgup1aW26JFT9.jpg",
    title: "The Stalker King",
    videoId: "kXFtB1epXa8",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Stalker King (2023)/The.Stalker.King.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"http://103.68.104.71//Admin/main/images/tt7825076/logo/tt7825076.png",
    rating: 2.67,
    year:2023,
    genre:[],
    category: "Thriller",
    length:"2h 39m",
  },
  {   id:5,
    img:"http://103.68.104.71//Admin/main/images/tt16437278/screen//cKqk1m6n2lPHZMHNSVYhrnRCiux.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt16437278/poster//3OKBFYRVSKkBVJ7WpKogTVQfUqC.jpg",
    title: "The Strays",
    videoId: "BzwOLKTbCUw",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Strays (2023)/The.Strays.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"http://103.68.104.71//Admin/main/images/tt16437278/logo/tt16437278.png",
    rating: 3.90,
    year:2020,
    genre:[],
    category: "Horror",
    length:"1h 49m",
  },
  {   id:6,
    img: "http://103.68.104.71//Admin/main/images/tt12672536/screen//f5pYm9znYtntwZYNoVG2tIfvpWq.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt12672536/poster//wve9qIZ8pXrDpHy1h47cGXHjZpH.jpg",
    title: "The Three Musketeers: D’Artagnan",
    videoId: "SAaSEZpa4cE",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Three Musketeers (2023)/The.Three.Musketeers.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"http://103.68.104.71//Admin/main/images/tt12672536/logo/tt12672536.png",
    rating: 4.82,
    year:2029,
    genre:[],
    category: "Adventure",
    length:"1h 29m",
  },
  {   id:7,
    img: "http://103.68.104.71//Admin/main/images/tt16916320/screen//4eC0tsU9OxR3Adlo1yRJYUDraW9.jpg",
    lThumb:"http://103.68.104.71//Admin/main/images/tt16916320/poster//hVh4hMzkXNLnScudbid6hDvjMPk.jpg",
    title: "The Siege",
    videoId: "cKC5sw4mojA",
    movieLink:"http://103.68.104.71/Data/movies/hollywood/2023/The Siege (2023)/The.Siege.2023.720p.WEBRip.x264.AAC-[YTS.MX].mp4",
    titleImg:"http://103.68.104.71//Admin/main/images/tt16916320/logo/tt16916320.png",
    rating: 4.70,
    year:2017,
    genre:[],
    category: "Action",
    length:"1h 45m",
  },


]
const allLiveTvData = [
  {
    id: 0,
    title: 'Movies',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 1,
    title: 'TV Series',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 2,
    title: 'Genre',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 3,
    title: 'Live TV',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 4,
    title: 'Request',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 5,
    title: 'Movies',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 6,
    title: 'TV Series',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 7,
    title: 'Genre',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 8,
    title: 'Live TV',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 9,
    title: 'Request',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 10,
    title: 'Movies',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 11,
    title: 'TV Series',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 12,
    title: 'Genre',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 13,
    title: 'Live TV',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
  {
    id: 14,
    title: 'Request',
    link: '',
    submenu: [],
    img: "/assets/images/Group 302.png"
  },
];
var continueWatchingData=[
  {
    id:0,
    title:"Killer",
    thumb:"./assets/images/continue-watching/0.png",
    imdbRating:8.5,
    watchDate:"2023-12-17",
    watchTime:20,
    remainingTime:"2h 17m remaining"
  },
  {
    id:1,
    title:"Noah",
    thumb:"./assets/images/continue-watching/1.png",
    imdbRating:8.5,
    watchDate:"2023-12-17",
    watchTime:30,
    remainingTime:"2h 17m remaining"
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"./assets/images/continue-watching/2.png",
    imdbRating:8.5,
    watchDate:"2023-12-16",
    watchTime:75,
    remainingTime:"2h 17m remaining"
  },
  {
    id:3,
    title:"Kill",
    thumb:"./assets/images/continue-watching/3.png",
    imdbRating:8.5,
    watchDate:"2023-12-15",
    watchTime:10,
    remainingTime:"2h 17m remaining"
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"./assets/images/continue-watching/4.png",
    imdbRating:8.5,
    watchDate:"2023-12-20",
    watchTime:50,
    remainingTime:"2h 17m remaining"
  },

];
var recentlyAddedData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",

  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",

  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",

  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",

  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",

  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",

  },

];
var recommendedForYouData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var topMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var hollywoodMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var bollywoodMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var animationMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var banglaMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var tamilMoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var hindiDubbedData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var teleguDubbedData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];
var imdbTop250MoviesData=[
  {
    id:0,
    title:"Killer",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:1,
    title:"Noah",
    thumb:"/assets/images/recentlyAdded/1.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:2,
    title:"Gardian Galaxy",
    thumb:"/assets/images/recentlyAdded/2.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:3,
    title:"Kill",
    thumb:"/assets/images/recentlyAdded/3.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2019,
    printType:"720 Blue-Ray",
  },
  {
    id:4,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/4.png",
    imdbRating:8.5,
    releaseYear:2020,
    printType:"720 Blue-Ray",
  },
  {
    id:5,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/5.png",
    imdbRating:8.5,
    releaseYear:2021,
    printType:"720 Blue-Ray",
  },
  {
    id:6,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/6.png",
    imdbRating:8.5,
    releaseYear:2022,
    printType:"720 Blue-Ray",
  },
  {
    id:7,
    title:"Unchartered",
    thumb:"/assets/images/recentlyAdded/7.png",
    imdbRating:8.5,
    releaseYear:2023,
    printType:"720 Blue-Ray",
  },

];

const liveTVsliderData = [
  { id: 0, name: "Desh TV" },
  { id: 1, name: "Baishakhi TV" },
  { id: 2, name: "NTV" },
  { id: 3, name: "Channel 24" },
  { id: 4, name: "ATN Bangla" },
  { id: 5, name: "Banglavision" },
  { id: 6, name: "Maasranga Television" },
  { id: 7, name: "Boishakhi Television" },
  { id: 8, name: "Gazi TV" },
  { id: 9, name: "Asian TV" }
];

